<?php
/**
 * @file
 * The IG Commerce Utility Products module.
 */
 
/**
 * Declare what blocks are provided by this module.
 * Implements hook_block_info().
 */
function igcommerce_utility_products_block_info() {
    $block['Product Recall'] = array(
        'info' => t('Product Recall'),
        'cache' => DRUPAL_NO_CACHE,
    );
    return $block;
}

/**
 * Define what the block is going to look like.
 * Implements hook_block_view().
 */
function igcommerce_utility_products_block_view($block_key) {
    $block = array();

    if ($block_key == 'Product Recall') {
      //We only want to define the content of OUR block
      //This is the title of the block.
      //$block['subject'] = t('Product Recall Title');

      //Define the block content
      $block['content'] = check_product_recall();
    }

    return $block;
}

/*Query product recall view and create html if products found
*/
function check_product_recall() {
  $prod_found = views_get_view_result('products_from_solr', 'product_recalls');
  $return_html = '<section><div class="col-xs-12 recall"><p><a href="/en/recalls"><span class="recall_home_title">' . t('Safety Recall') . '</span></a>' . ': ' . t('Refer to the Product Recall page for details.') . '<a href="/en/recalls">' . t('Read More') . '</a></p></div></section>';
  if (!empty($prod_found)) {
    return $return_html;
  }
  else{
    return '';
  }
}